version: '3.9'
services:
  db:
    image: mysql:8.0.21
    container_name: mysql_db
    platform: linux/x86_64 #para usar no mac
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=123456
